version: "3.9"

services:
  postgis:
    image: postgis/postgis
    container_name: postgis
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    expose:
      - 5432
#    volumes:
#      - volume-es:/usr/share/elasticsearch/data
#    networks:
#      - network
#networks:
#  network:
#
#volumes:
#  volume-es: